# Generated by Django 3.2.12 on 2023-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParamets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plot', models.IntegerField(default=1)),
                ('number_equipment', models.IntegerField(default=1)),
                ('number_node', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('date_of_repair', models.IntegerField(default=1)),
                ('replaced_parts', models.CharField(max_length=255)),
                ('next_replacement_date', models.IntegerField(default=1)),
            ],
        ),
    ]
